### ISSUE TITLE
Remove Bash and Git software requirements

### ISSUE THREAD

**Issue by ldko** [unt-carpentries/2021-03-10-unt-lc#1]
Thanks for setting up our workshop page, Chassidy! I am thinking the OpenRefine portion of the workshop doesn't use Bash and Git... if that is the case, I recommend we remove those sections from the workshop info.

**Comment by cmil-2** [comment]
No problem! I removed Bash and Git from the software requirements.

**Comment by ldko** [comment]
Thanks, looks great!
